version: "3.8"

services:
  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: product
      PROD: False
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - database
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  server:
    build:
      context: ./
      args:
        - DEV=true
    networks:
      - database
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - ./:/ProductManagement
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    environment:
      DB_HOST: postgres
      DB_NAME: product
      DB_USER: postgres
      DB_PASS: postgres
      DB_PORT: 5432
    restart: always

networks:
  database:
    driver: bridge
  web:
    driver: bridge
volumes:
  postgres-data: